services:
  backspace-agent:
    build: .
    ports:
      - "9000:8000"
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - LOG_FORMAT=console
    env_file:
      - .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app/app
    depends_on:
      - jaeger
    networks:
      - backspace-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - backspace-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - backspace-network

networks:
  backspace-network:
    driver: bridge

volumes:
  redis-data: 